name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        pg: [13, 12, 11, 10]
        ccflags: ['']
        include:
          - pg: 13
            ccflags: '-DCACHING_TEST'
    name: PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: zilder/pg-ext-check
    steps:
      - run: pg-setup ${{ matrix.pg }}
      - uses: actions/checkout@v2
      - run: ./install_arrow.sh
      - run: build-check
        env:
          CCFLAGS: ${{ matrix.ccflags }}
